
grammars=$(HOME)/.cabal/share/gf-3.3.3/www/grammars/

all: help

help:
	@echo Targets:
	@echo
	@echo "grammars:  list installed grammars"
	@echo "    test:  run a small test"


ls_grammars:
	ls -la $(grammars)

test:
	sh test_gfws.sh
